default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: guildhub_development

test:
  <<: *default
  database: guildhub_test

production:
  <<: *default
  database: guildhub_production
  username: guildhub
  password: <%= ENV["GUILDHUB_DATABASE_PASSWORD"] %>
