# Redis Configuration for GuildHub
# Used for: Caching, ActionCable, Solid Queue, Sessions

default: &default
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379" } %>
  timeout: 1
  reconnect_attempts: 3

development:
  <<: *default
  # Development uses database 0
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>

test:
  <<: *default
  # Test uses database 1 to avoid conflicts
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

production:
  <<: *default
  # Production uses database 0
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/0" } %>
  # Production-specific settings
  timeout: 5
  reconnect_attempts: 5
  # Enable SSL in production if needed
  # ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
